---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-v1
  labels:
    name: collector
    app: collector
    version: v1
  namespace: hawk-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      name: collector
      app: collector
      version: v1
  template:
    metadata:
      labels:
        name: collector
        app: collector
        version: v1
    spec:
      containers:
        - name: collector
          image: jmgoyesc/collector
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://collector-db/admin"
            - name: SPRING_DATASOURCE_USERNAME
              value: "coll_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "collector_pasword"
            - name: SPRING_SQL_INIT_DATA_LOCATIONS
              value: classpath:default-data.sql
            - name: SERVER_PORT
              value: "8080"
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
