apiVersion: v1
kind: Service
metadata:
  name: collector
  labels:
    name: collector
    app: collector
  namespace: hawk-ns
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8080
  selector:
    name: collector
    app: collector
