apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: hawk-ns
spec:
  selector:
    app: rabbitmq
  ports:
    - name: queue
      port: 5672
      targetPort: 5672
    - name: admin
      port: 15672
      targetPort: 15672
