apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: hawk-ns
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
        sidecar.istio.io/inject: "false"
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
      - name: grafana
        image: grafana/grafana:8.1.2
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: GF_INSTALL_PLUGINS
            value: simpod-json-datasource,novatec-sdg-panel
